name: worK
options:
  bundleIdPrefix: com.worK
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"
  generateEmptyDirectories: true
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.worK.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_LSUIElement: true
    INFOPLIST_KEY_LSMinimumSystemVersion: "15.0"
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_ENTITLEMENTS: worK/Resources/worK.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  debug:
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
  release:
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
packages:
  sqlite-data:
    url: https://github.com/pointfreeco/sqlite-data
    from: "1.6.0"
  swift-dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.11.0"
  swift-snapshot-testing:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: "1.18.3"
schemes:
  worK:
    build:
      targets:
        worK: all
        worKTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - worKTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  worK:
    type: application
    platform: macOS
    sources:
      - path: worK
        excludes:
          - "Resources/Info.plist"
    resources:
      - path: worK/Resources/Assets.xcassets
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
    dependencies:
      - package: sqlite-data
        product: SQLiteData
      - package: swift-dependencies
        product: Dependencies
      - package: swift-dependencies
        product: DependenciesMacros
      - sdk: ServiceManagement.framework
      - sdk: AppKit.framework
  worKTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: worKTests
        excludes:
          - "**/__Snapshots__/**"
      - path: worK
        excludes:
          - "Resources/Info.plist"
          - "App/worKApp.swift"
          - "App/AppDelegate.swift"
          - "StatusBar/StatusBarController.swift"
          - "Dependencies/DatabaseBootstrap.swift"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: swift-snapshot-testing
        product: SnapshotTesting
      - package: sqlite-data
        product: SQLiteData
      - package: swift-dependencies
        product: Dependencies
      - package: swift-dependencies
        product: DependenciesMacros
      - sdk: ServiceManagement.framework
      - sdk: AppKit.framework
